[versions]
accompanistSystemuicontroller = "0.34.0"
agp = "8.7.3"
androidxMedia3Media3Exoplayer4 = "1.6.0"
androidxMedia3Media3Ui2 = "1.6.0"
basepopup = "3.2.1"
coilCompose = "2.6.0"
composeLivedata = "1.7.8"
easypermissions = "3.0.0"
eventbusVersion = "3.3.1"
ksp = "1.9.23-1.0.19"
kotlin = "1.9.23"
coreKtx = "1.13.1"
junit = "4.13.2"
lifecycleRuntimeKtx = "2.8.7"
activityCompose = "1.10.1"
composeBom = "2025.03.01"
appcompat = "1.7.0"
room = "2.6.1"
navigationCompose = "2.8.9"
xcrash = "3.0.0"
pagingCommonAndroid = "3.3.6"
pagingCompose = "3.3.6"
gmaps = "2.0.1"
material3 = "1.3.1"
composeMarkdown = "0.5.4"
lfilepickerlibrary = "1.8.0"
sceneview = "2.2.1"
gson = "2.10.1"
retrofit = "2.9.0"
converterGson = "2.9.0"
loggingInterceptor = "4.11.0"
jts = "1.18.0"
mapbox = "10.16.0"
googlemap = "18.2.0"
androidx-lifecycle = "2.6.2"
kotlinx-coroutines = "1.7.3"

[libraries]
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanistSystemuicontroller" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-media3-media3-ui4 = { module = "androidx.media3:media3-ui", version.ref = "androidxMedia3Media3Ui2" }
androidx-media3-media3-exoplayer6 = { module = "androidx.media3:media3-exoplayer", version.ref = "androidxMedia3Media3Exoplayer4" }
basepopup = { module = "io.github.razerdp:BasePopup", version.ref = "basepopup" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coilCompose" }
easypermissions = { module = "pub.devrel:easypermissions", version.ref = "easypermissions" }
greenrobot-eventbus = { module = "org.greenrobot:eventbus", version.ref = "eventbusVersion" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-runtime-livedata = { group = "androidx.compose.runtime", name = "runtime-livedata", version.ref = "composeLivedata" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-ksp = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
xcrash-android-lib = { module = "com.iqiyi.xcrash:xcrash-android-lib", version.ref = "xcrash" }
androidx-paging-common-android = { group = "androidx.paging", name = "paging-common-android", version.ref = "pagingCommonAndroid" }
androidx-paging-compose = { group = "androidx.paging", name = "paging-compose", version.ref = "pagingCompose" }
compose-markdown = { module = "com.github.jeziellago:compose-markdown", version.ref = "composeMarkdown" }
lfilepickerlibrary = { module = "com.leon:lfilepickerlibrary", version.ref = "lfilepickerlibrary" }
sceneview = { module = "io.github.sceneview:sceneview", version.ref = "sceneview" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
converterGson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "converterGson" }
loggingInterceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "loggingInterceptor" }
jts = { module = "org.locationtech.jts:jts-core", version.ref = "jts" }
mapbox = { module = "com.mapbox.maps:android", version.ref = "mapbox" }
googlemap = { module = "com.google.android.gms:play-services-maps", version.ref = "googlemap" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
googleKsp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
googleAndroidMapsPlugin = { id = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin", version.ref = "gmaps" }
